data:
  root_dir: /data1/DALLE-datasets/general/cc12
  ix_file: ixs_filtered.txt
  res: 256
  img_folder: images

  val_size: 8
  seed: 42
  batch_size: 64
  num_workers: 128

trainer:
  gpus: 8
  strategy: ddp_find_unused_parameters_false
  auto_lr_find: True
  val_check_interval: 0.02
  log_every_n_steps: 1
  gradient_clip_val: 0.5
  gradient_clip_algorithm: value
  # resume_from_checkpoint: /data2/vqvae-ckpt/hybrid/1/last.ckpt